export class LanguageConfig {
  public static languageMap: Record<string, string> = {
    'und': '未知',
    'chi': '中文',
    'jpn': '日语',
    'eng': '英语',
    'kor': '韩语',
    'fre': '法语',
    'ger': '德语',
    'spa': '西班牙语',
    'rus': '俄语',
    'ara': '阿拉伯语',
    'por': '葡萄牙语',
    'ita': '意大利语',
    'hin': '印地语',
    'tha': '泰语',
    'urk': '乌克兰语',
    'thr': '土耳其语',
    'ind': '印尼语',
    'dut': '荷兰语',
    'swe': '瑞典语'
  }
}