export default class NavigationAddress {
  static AV_PLAYER = 'player'
  static FFMPEG_PLAYER = 'FFMpegPlayer'
  static RED_PLAYER = 'RedPlayer'
  static SETTING_PAGE = 'SettingsPage'
  static ABOUT_PAGE = 'AboutPage'
  static RECENT_PLAY = 'RecentPlay'
  static PRIVACY_SPACE = 'PrivacySpace'
  static CRASH_PAGE = 'CrashPage'
  static PERSONALIZE_PAGE = 'PersonalizePage'
  static PLAYER_SETTING_PAGE = 'PlayerSettingPage'
}